// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkEWjFg_CIBk5Zkg0oTSlwqKEpy8HpENQ',
    appId: '1:1041657535682:web:6ae2e186526789330e6f5b',
    messagingSenderId: '1041657535682',
    projectId: 'flutter-chat-57196',
    authDomain: 'flutter-chat-57196.firebaseapp.com',
    storageBucket: 'flutter-chat-57196.firebasestorage.app',
    measurementId: 'G-KTEFS5QK9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYNhKwQ4LpH5Le7o5kaWt0xPydqTsiV4',
    appId: '1:1041657535682:android:6754159ccf8159eb0e6f5b',
    messagingSenderId: '1041657535682',
    projectId: 'flutter-chat-57196',
    storageBucket: 'flutter-chat-57196.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvflQfr4_FAAFNCF228dsy_bZLDl8XNH8',
    appId: '1:1041657535682:ios:d801eaeea388da3c0e6f5b',
    messagingSenderId: '1041657535682',
    projectId: 'flutter-chat-57196',
    storageBucket: 'flutter-chat-57196.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvflQfr4_FAAFNCF228dsy_bZLDl8XNH8',
    appId: '1:1041657535682:ios:d801eaeea388da3c0e6f5b',
    messagingSenderId: '1041657535682',
    projectId: 'flutter-chat-57196',
    storageBucket: 'flutter-chat-57196.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkEWjFg_CIBk5Zkg0oTSlwqKEpy8HpENQ',
    appId: '1:1041657535682:web:4ff060196e58d3db0e6f5b',
    messagingSenderId: '1041657535682',
    projectId: 'flutter-chat-57196',
    authDomain: 'flutter-chat-57196.firebaseapp.com',
    storageBucket: 'flutter-chat-57196.firebasestorage.app',
    measurementId: 'G-F6ECVHZQ22',
  );

}